theme: jekyll-theme-hacker
title: "Welcome to the Mike's homepage!"
description: "Various things I do outside of work: fun, boring, anything really."

google_analytics: "UA-180870978-1"

author:
  name: "Mike Krinkin"
  location: "Dublin, Ireland"
  email: "krinkin.m.u@gmail.com"
  github: "krinkinmu"
